# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://podcast.umputun.com
title: Еженедельный подкаст от Umputun
subtitle: Невыдуманные рассказы из американской жизни
author: Umputun
simple_search: https://google.com/search
description: Невыдуманные рассказы из моей жизни в Чикаго (и не только), различные рассуждения и наблюдения, немного компьютерных разговоров, совсем чуть-чуть политики и порой немного юмора.

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%d-%m-%Y"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: http://feeds.rucast.net/Umputun
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /p/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 12          # Posts per page on the blog index
pagination_dir: p  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Далее &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [custom/asides/about.html, custom/asides/feeds.html, custom/asides/useful.html, custom/asides/contacts.html, custom/asides/help.html, custom/asides/ads.html, custom/asides/disqus.html, custom/asides/twitter.html, custom/asides/buttons.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: umputun
twitter_tweet_count: 10
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: xxxxxxxxxxx
googleplus_hidden: yes
googleplus_profile_display: none
googleplus_post_display: block
googleplus_post_amount: 10

# Google Api Console
google_api_key: xxxxxxxxxxx

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: UWP
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: xxxxxxxx

# Facebook Like
facebook_like: false
